[project]
name = "text-extraction-pipeline"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "accelerate==1.12.0",
    "pandas==2.3.3",
    "streamlit==1.54.0",
    "torch==2.10.0",
    "transformers==5.1.0",
]

[dependency-groups]
dev = [
    "pytest==9.0.2",
    "ruff==0.15.0",
    "ty==0.0.16",
]
